/** Vivienda Nova: importación privada de cartera desde CSV, validada antes de crear fichas. */
import { ChangeEvent, useMemo, useState } from "react";
import { AlertTriangle, Check, Download, FileSpreadsheet, Loader2, Upload, X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import "./PropertyImporter.css";

type ImportProperty = { slug: string; title: string; address: string; city: string; zone: string; province: string | null; country: string; type: string; price: string; priceValue: number; bedrooms: number; bathrooms: number; surface: number; description: string; imageUrl: string; tag: string; status: "draft" | "published"; linkMode: "capture" | "redirect" | "both"; vendorId: number | null; externalUrl: string | null; referralParameter: string; referralCode: string | null; };
type Result = { rows: ImportProperty[]; errors: string[] };

const columns = ["title", "slug", "address", "city", "zone", "province", "country", "type", "price", "priceValue", "bedrooms", "bathrooms", "surface", "description", "imageUrl", "tag", "status", "linkMode", "vendorId", "externalUrl", "referralParameter", "referralCode"] as const;
const mandatory = ["title", "city", "zone", "price", "pricevalue", "bedrooms", "bathrooms", "surface", "description", "imageurl", "status", "linkmode"] as const;

function slugify(value: string) { return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "").slice(0, 180); }
function parseRows(raw: string) { const rows: string[][] = []; let value = ""; let row: string[] = []; let quoted = false; for (let index = 0; index < raw.length; index += 1) { const char = raw[index]; const next = raw[index + 1]; if (char === '"' && quoted && next === '"') { value += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if (!quoted && (char === ";" || char === ",")) { row.push(value.trim()); value = ""; } else if (!quoted && (char === "\n" || char === "\r")) { if (char === "\r" && next === "\n") index += 1; row.push(value.trim()); if (row.some(Boolean)) rows.push(row); row = []; value = ""; } else value += char; } row.push(value.trim()); if (row.some(Boolean)) rows.push(row); return rows; }
function normalizeHeader(value: string) { return value.replace(/^\uFEFF/, "").trim().toLowerCase(); }
export function readCsv(raw: string): Result { const table = parseRows(raw); if (table.length < 2) return { rows: [], errors: ["El archivo debe contener una cabecera y al menos una vivienda."] }; const headers = table[0].map(normalizeHeader); const errors = mandatory.filter((field) => !headers.includes(field)).map((field) => `Falta la columna obligatoria «${field}».`); if (errors.length) return { rows: [], errors }; const rows: ImportProperty[] = []; table.slice(1).forEach((line, index) => { const record = Object.fromEntries(headers.map((header, column) => [header, line[column]?.trim() ?? ""])); const rowNumber = index + 2; const missing = mandatory.filter((field) => !record[field]); if (missing.length) { errors.push(`Fila ${rowNumber}: faltan ${missing.join(", ")}.`); return; } const priceValue = Number(record.pricevalue); const bedrooms = Number(record.bedrooms); const bathrooms = Number(record.bathrooms); const surface = Number(record.surface); if (![priceValue, bedrooms, bathrooms, surface].every(Number.isFinite) || priceValue < 0 || bedrooms < 0 || bathrooms < 0 || surface <= 0) { errors.push(`Fila ${rowNumber}: revisa precio y características numéricas.`); return; } const status = record.status.toLowerCase(); const linkMode = record.linkmode.toLowerCase(); if (!["draft", "published"].includes(status) || !["capture", "redirect", "both"].includes(linkMode)) { errors.push(`Fila ${rowNumber}: status debe ser draft/published y linkMode capture/redirect/both.`); return; } const externalUrl = record.externalurl || null; if (status === "published" && (!externalUrl || linkMode === "capture")) { errors.push(`Fila ${rowNumber}: una vivienda publicada necesita externalUrl y linkMode redirect o both.`); return; } try { if (externalUrl) new URL(externalUrl); new URL(record.imageurl); } catch { errors.push(`Fila ${rowNumber}: imageUrl o externalUrl no tienen una URL válida.`); return; } rows.push({ slug: record.slug || slugify(record.title), title: record.title, address: record.address, city: record.city, zone: record.zone, province: record.province || null, country: record.country || "España", type: record.type || "Piso", price: record.price, priceValue, bedrooms, bathrooms, surface, description: record.description, imageUrl: record.imageurl, tag: record.tag || "Nueva oportunidad", status: status as ImportProperty["status"], linkMode: linkMode as ImportProperty["linkMode"], vendorId: record.vendorid ? Number(record.vendorid) : null, externalUrl, referralParameter: record.referralparameter || "ref", referralCode: record.referralcode || "MARTINEZ" }); }); return { rows, errors }; }
function templateCsv() { return `${columns.join(";")}\nVilla del Roble;villa-del-roble;Calle de ejemplo 1;Marbella;Sierra Blanca;Málaga;España;Casa;1250000 €;1250000;4;3;260;Vivienda con luz natural y jardín.;https://ejemplo.com/foto.jpg;Nueva oportunidad;draft;redirect;;https://vendedor.example/villa-del-roble;ref;MARTINEZ`; }

export default function PropertyImporter({ onClose, onCompleted }: { onClose: () => void; onCompleted: () => Promise<void> }) {
  const createProperty = trpc.admin.createProperty.useMutation();
  const [result, setResult] = useState<Result>({ rows: [], errors: [] });
  const [fileName, setFileName] = useState("");
  const [isImporting, setIsImporting] = useState(false);
  const ready = result.rows.length > 0 && result.errors.length === 0;
  const preview = useMemo(() => result.rows.slice(0, 4), [result.rows]);
  const downloadTemplate = () => { const url = URL.createObjectURL(new Blob([templateCsv()], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "plantilla-vivienda-nova.csv"; anchor.click(); URL.revokeObjectURL(url); };
  const selectFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!file.name.toLowerCase().endsWith(".csv") || file.size > 1_000_000) { setResult({ rows: [], errors: ["Selecciona un archivo CSV de hasta 1 MB."] }); return; } const reader = new FileReader(); reader.onload = () => { setFileName(file.name); setResult(readCsv(String(reader.result ?? ""))); }; reader.readAsText(file, "utf-8"); };
  const importRows = async () => { if (!ready) return; setIsImporting(true); try { for (const row of result.rows) await createProperty.mutateAsync(row); await onCompleted(); toast.success(`${result.rows.length} vivienda${result.rows.length === 1 ? " creada" : "s creadas"} correctamente.`); onClose(); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo importar una de las viviendas. No se han eliminado las fichas ya creadas."); } finally { setIsImporting(false); } };
  return <section className="csv-importer" aria-labelledby="csv-title"><div className="csv-importer__heading"><div><p className="admin-kicker"><span /> Actualización por archivo</p><h2 id="csv-title">Importar <em>viviendas.</em></h2></div><button type="button" className="editor-close" onClick={onClose}><X size={16} /> Cerrar</button></div><p className="csv-importer__intro">Carga un archivo CSV para crear varias fichas. Primero verás los errores y una vista previa; no se guardará nada hasta pulsar «Importar viviendas».</p><div className="csv-importer__actions"><button type="button" className="csv-template" onClick={downloadTemplate}><Download size={17} /> Descargar plantilla CSV</button><label className="csv-upload"><Upload size={17} /> Elegir archivo<input type="file" accept=".csv,text/csv" onChange={selectFile} /></label></div><p className="csv-importer__hint">Campos obligatorios: título, ciudad, zona, precio, características, descripción, imagen, estado y flujo. Las viviendas publicadas requieren un enlace al vendedor.</p>{fileName && <div className="csv-file"><FileSpreadsheet size={19} /><span>{fileName}</span>{ready ? <b><Check size={15} /> Listo para revisar</b> : <b className="is-error"><AlertTriangle size={15} /> Requiere corrección</b>}</div>}{result.errors.length > 0 && <div className="csv-errors"><strong><AlertTriangle size={17} /> Corrige el archivo antes de importar</strong><ul>{result.errors.slice(0, 8).map((error) => <li key={error}>{error}</li>)}</ul>{result.errors.length > 8 && <p>Y {result.errors.length - 8} errores más.</p>}</div>}{ready && <><div className="csv-preview"><div><strong>{result.rows.length} vivienda{result.rows.length === 1 ? "" : "s"} preparada{result.rows.length === 1 ? "" : "s"}</strong><span>Vista previa de las cuatro primeras fichas</span></div><table><thead><tr><th>Título</th><th>Zona</th><th>Precio</th><th>Estado</th></tr></thead><tbody>{preview.map((item) => <tr key={item.slug}><td>{item.title}</td><td>{item.zone} · {item.city}</td><td>{item.price}</td><td>{item.status === "published" ? "Publicada" : "Borrador"}</td></tr>)}</tbody></table></div><div className="csv-importer__confirm"><p>Al importar se crearán las fichas y se prepararán sus traducciones según los idiomas activos.</p><button type="button" className="admin-primary" disabled={isImporting} onClick={importRows}>{isImporting ? <><Loader2 className="spin" size={16} /> Importando…</> : <><Upload size={16} /> Importar viviendas</>}</button></div></>}</section>;
}
